apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy   # base64 of 'mongouser'
  mongo-password: bW9uZ29wYXNz # base64 of 'mongopass'
  mongo-uri: bW9uZ29kYjovL21vbmdvdXNlcixtb25nb3Bhc3M=
